#makefile

DEBUG_FLAG= -DDEBUG -g -Wall
CFLAGS=-DDEBUG -g -Wall

.SUFFIXES: .cpp .o

.cpp.o:
	g++ $(CFLAGS) -c $<

Binary: BIN.o Instruction.o OpcodeTable.o RegisterTable.o BinaryParser.o
	g++ -o ASM ASM.o OpcodeTable.o ASMParser.o RegisterTable.o Instruction.o

BinaryParser.o: BinaryParser.h OpcodeTable.h RegisterTable.h Instruction.h 

Instruction.o: OpcodeTable.h RegisterTable.h Instruction.h 

OpcodeTable.o: OpcodeTable.h 

RegisterTable.o: RegisterTable.h  

clean:
	/bin/rm -f ASM *.o core

